/**
 * Export utilities for comparison data.
 * Supports Markdown and CSV formats.
 */

import { QuadrantIndex } from '../Output';

export interface ComparisonResult {
  quadrant: QuadrantIndex;
  encoderName: string;
  quality: number;
  originalSize: number;
  compressedSize: number;
  compressionRatio: number;
  ssim: number;
  encodeTime: number;
  isOptimal?: boolean;
}

export interface ExportOptions {
  includeOriginal?: boolean;
  format?: 'markdown' | 'csv';
  timestamp?: boolean;
}

function formatBytes(bytes: number, decimals: number = 2): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(decimals)) + ' ' + sizes[i];
}

function formatTime(ms: number): string {
  if (ms < 1000) return `${ms.toFixed(2)}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function formatRatio(ratio: number): string {
  const percent = (1 - ratio) * 100;
  if (percent > 0) {
    return `${percent.toFixed(1)}% smaller`;
  }
  return `${Math.abs(percent).toFixed(1)}% larger`;
}

export function exportToMarkdown(
  results: ComparisonResult[],
  options: ExportOptions = {},
): string {
  const { includeOriginal = true, timestamp = true } = options;
  const lines: string[] = [];

  lines.push('# Image Compression Comparison');
  lines.push('');

  if (timestamp) {
    lines.push(`*Generated at: ${new Date().toISOString()}*`);
    lines.push('');
  }

  lines.push('## Summary');
  lines.push('');

  lines.push('| Encoder | Quality | Original | Compressed | Ratio | SSIM | Time |');
  lines.push('|---------|---------|----------|------------|-------|------|------|');

  const sortedResults = [...results].sort((a, b) => {
    if (a.ssim >= 0.95 && b.ssim < 0.95) return -1;
    if (a.ssim < 0.95 && b.ssim >= 0.95) return 1;
    return a.compressedSize - b.compressedSize;
  });

  for (const result of sortedResults) {
    const optimal = result.isOptimal ? '⭐ ' : '';
    lines.push(
      `| ${optimal}${result.encoderName} | ${result.quality.toFixed(
        1,
      )} | ${formatBytes(result.originalSize)} | ${formatBytes(
        result.compressedSize,
      )} | ${formatRatio(result.compressionRatio)} | ${result.ssim.toFixed(
        4,
      )} | ${formatTime(result.encodeTime)} |`,
    );
  }

  lines.push('');

  const validResults = results.filter((r) => r.ssim >= 0.95);
  if (validResults.length > 0) {
    lines.push('## Top Performers (SSIM ≥ 0.95)');
    lines.push('');

    const bestSize = validResults.sort((a, b) => a.compressedSize - b.compressedSize)[0];
    const fastest = validResults.sort((a, b) => a.encodeTime - b.encodeTime)[0];
    const highestQuality = validResults.sort((a, b) => b.ssim - a.ssim)[0];

    lines.push(
      `- **Smallest file**: ${bestSize.encoderName} (${formatBytes(
        bestSize.compressedSize,
      )}, SSIM: ${bestSize.ssim.toFixed(4)})`,
    );
    lines.push(
      `- **Fastest encode**: ${fastest.encoderName} (${formatTime(
        fastest.encodeTime,
      )}, SSIM: ${fastest.ssim.toFixed(4)})`,
    );
    lines.push(
      `- **Highest quality**: ${highestQuality.encoderName} (SSIM: ${highestQuality.ssim.toFixed(
        4,
      )}, ${formatBytes(highestQuality.compressedSize)})`,
    );
    lines.push('');
  }

  lines.push('## Details');
  lines.push('');

  for (const result of results) {
    const optimal = result.isOptimal ? ' ⭐ Optimal' : '';
    lines.push(`### ${result.encoderName}${optimal}`);
    lines.push('');
    lines.push(`- **Quality**: ${result.quality.toFixed(1)}`);
    lines.push(`- **Original size**: ${formatBytes(result.originalSize)}`);
    lines.push(`- **Compressed size**: ${formatBytes(result.compressedSize)}`);
    lines.push(
      `- **Compression ratio**: ${(result.compressionRatio * 100).toFixed(
        1,
      )}% of original (${formatRatio(result.compressionRatio)})`,
    );
    lines.push(`- **SSIM**: ${result.ssim.toFixed(4)}`);
    lines.push(`- **Encode time**: ${formatTime(result.encodeTime)}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '*Generated by Squoosh Quadrant Comparison - 4-codec comparison tool*',
  );

  return lines.join('\n');
}

export function exportToCSV(
  results: ComparisonResult[],
  options: ExportOptions = {},
): string {
  const { timestamp = true } = options;
  const lines: string[] = [];

  if (timestamp) {
    lines.push(`# Generated at: ${new Date().toISOString()}`);
  }

  lines.push(
    'Encoder,Quality,OriginalSize,CompressedSize,CompressionRatio,SSIM,EncodeTimeMs,IsOptimal',
  );

  for (const result of results) {
    lines.push(
      [
        `"${result.encoderName}"`,
        result.quality.toFixed(2),
        result.originalSize,
        result.compressedSize,
        result.compressionRatio.toFixed(6),
        result.ssim.toFixed(6),
        result.encodeTime.toFixed(2),
        result.isOptimal ? 'TRUE' : 'FALSE',
      ].join(','),
    );
  }

  return lines.join('\n');
}

export function downloadString(
  content: string,
  filename: string,
  mimeType: string = 'text/plain',
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(
  results: ComparisonResult[],
  filename: string = 'comparison.md',
): void {
  const content = exportToMarkdown(results);
  downloadString(content, filename, 'text/markdown');
}

export function downloadCSV(
  results: ComparisonResult[],
  filename: string = 'comparison.csv',
): void {
  const content = exportToCSV(results);
  downloadString(content, filename, 'text/csv');
}
